apiVersion: bindplane.observiq.com/v1
kind: Destination
metadata:
    name: external-gw-kind-2
spec:
    type: otlp_grpc
    parameters:
        - name: telemetry_types
          value:
            - Logs
            - Metrics
            - Traces
        - name: hostname
          value: 172.18.0.3 # TODO: change to the actual hostname
        - name: grpc_port
          value: 30317
        - name: http_port
          value: 4318
        - name: protocol
          value: grpc
        - name: http_path_prefix
          value: ""
        - name: headers
          value: {}
        - name: http_compression
          value: gzip
        - name: grpc_compression
          value: gzip
        - name: timeout
          value: 30
        - name: enable_grpc_load_balancing
          value: false
        - name: grpc_load_balancing_policy
          value: round_robin
        - name: enable_tls
          value: false
        - name: insecure_skip_verify
          value: false
        - name: ca_file
          value: ""
        - name: tls_server_name_override
          value: ""
        - name: mutual_tls
          value: false
        - name: cert_file
          value: ""
        - name: key_file
          value: ""
        - name: drop_raw_copy
          value: true
        - name: retry_on_failure_enabled
          value: true
        - name: retry_on_failure_initial_interval
          value: 5
        - name: retry_on_failure_max_interval
          value: 30
        - name: retry_on_failure_max_elapsed_time
          value: 300
        - name: sending_queue_enabled
          value: true
        - name: sending_queue_num_consumers
          value: 10
        - name: sending_queue_queue_size
          value: 5000
        - name: persistent_queue_enabled
          value: true
        - name: persistent_queue_directory
          value: ${OIQ_OTEL_COLLECTOR_HOME}/storage
