---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: bindplane-agent
  name: bindplane-agent
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: bindplane-agent
  name: bindplane-agent
  namespace: bindplane-agent
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: bindplane-agent
    app.kubernetes.io/component: gateway
  name: bindplane-gateway-agent
  namespace: bindplane-agent
spec:
  ports:
  - appProtocol: grpc
    name: otlp-grpc
    port: 4317
    protocol: TCP
    targetPort: 4317
  - appProtocol: http
    name: otlp-http
    port: 4318
    protocol: TCP
    targetPort: 4318
  - appProtocol: tcp
    name: splunk-tcp
    port: 9997
    protocol: TCP
    targetPort: 9997
  - appProtocol: tcp
    name: splunk-hec
    port: 8088
    protocol: TCP
    targetPort: 8088
  selector:
    app.kubernetes.io/name: bindplane-agent
    app.kubernetes.io/component: gateway
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: bindplane-agent
    app.kubernetes.io/component: gateway
  name: bindplane-gateway-agent-headless
  namespace: bindplane-agent
spec:
  clusterIP: None
  ports:
  - appProtocol: grpc
    name: otlp-grpc
    port: 4317
    protocol: TCP
    targetPort: 4317
  - appProtocol: http
    name: otlp-http
    port: 4318
    protocol: TCP
    targetPort: 4318
  selector:
    app.kubernetes.io/name: bindplane-agent
    app.kubernetes.io/component: gateway
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bindplane-gateway-agent
  labels:
    app.kubernetes.io/name: bindplane-agent
    app.kubernetes.io/component: gateway
  namespace: bindplane-agent
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: bindplane-agent
      app.kubernetes.io/component: gateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bindplane-agent
        app.kubernetes.io/component: gateway
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8888"
        prometheus.io/scheme: http
        prometheus.io/job-name: bindplane-gateway-agent
    spec:
      serviceAccount: bindplane-agent
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:  [bindplane-agent]
                    - key: app.kubernetes.io/component
                      operator: In
                      values: [gateway]
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000000000
        runAsGroup: 1000000000
        fsGroup: 1000000000
        seccompProfile:
          type: RuntimeDefault
      initContainers:
        - name: setup-volumes
          image: ghcr.io/observiq/bindplane-agent:1.80.1
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000000000
            runAsGroup: 1000000000
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          command:
            - 'sh'
            - '-c'
            - |
              echo '
              receivers:
                nop:
              processors:
                batch:
              exporters:
                nop:
              service:
                pipelines:
                  metrics:
                    receivers: [nop]
                    processors: [batch]
                    exporters: [nop]
                telemetry:
                  metrics:
                    level: none
              ' > /etc/otel/storage/config.yaml
              echo '
              output: stdout
              level: info
              ' > /etc/otel/storage/logging.yaml
          resources:
            requests:
              memory: 200Mi
              cpu: 100m
            limits:
              memory: 200Mi
          volumeMounts:
            - mountPath: /etc/otel/storage
              name: bindplane-gateway-agent-storage
      containers:
        - name: opentelemetry-container
          image: ghcr.io/observiq/bindplane-agent:1.80.1
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000000000
            runAsGroup: 1000000000
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              memory: 500Mi
              cpu: 250m
            limits:
              memory: 500Mi
          ports:
            - containerPort: 8888
              name: prometheus
          env:
            - name: OPAMP_ENDPOINT
              value: wss://app.bindplane.com/v1/opamp
            - name: OPAMP_SECRET_KEY
              value: <secret>
            - name: OPAMP_AGENT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPAMP_LABELS
              value: <labels>
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            # The collector process updates config.yaml
            # and manager.yaml when receiving changes
            # from the OpAMP server.
            - name: CONFIG_YAML_PATH
              value: /etc/otel/storage/config.yaml
            - name: MANAGER_YAML_PATH
              value: /etc/otel/config/manager.yaml
            - name: LOGGING_YAML_PATH
              value: /etc/otel/storage/logging.yaml
          volumeMounts:
          - mountPath: /etc/otel/storage
            name: bindplane-gateway-agent-storage
          - mountPath: /etc/otel/config
            name: config
      volumes:
        - name: config
          emptyDir: {}
        - name: bindplane-gateway-agent-storage
          emptyDir: {}
      # Allow exporters to drain their queue for up to
      # five minutes.
      terminationGracePeriodSeconds: 500
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bindplane-gateway-agent
  namespace: bindplane-agent
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bindplane-gateway-agent
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
