apiVersion: v1
kind: Service
metadata:
  name: bindplane-gateway-agent-nodeport
  namespace: bindplane-agent
  labels:
    app.kubernetes.io/name: bindplane-agent
    app.kubernetes.io/component: gateway
spec:
  type: NodePort
  ports:
  - name: otlp-grpc
    port: 4317
    targetPort: 4317
    nodePort: 30317
    protocol: TCP
  - name: otlp-http
    port: 4318
    targetPort: 4318
    nodePort: 30318
    protocol: TCP
  selector:
    app.kubernetes.io/name: bindplane-agent
    app.kubernetes.io/component: gateway
