# receivers:
#   nop:
# processors:
#   batch:
# exporters:
#   nop:
# service:
#   pipelines:
#     metrics:
#       receivers: [nop]
#       processors: [batch]
#       exporters: [nop]
#   telemetry:
#     metrics:
#       level: none
