# This configuration is managed by Bindplane.
# Configuration: gw:9
receivers:
    hostmetrics/_agent_health_metrics:
        collection_interval: 1m0s
        scrapers:
            process:
                include:
                    match_type: regexp
                    names:
                        - ^observiq-otel-collector(.exe)?$
                metrics:
                    process.context_switches:
                        enabled: false
                    process.cpu.time:
                        enabled: false
                    process.cpu.utilization:
                        enabled: true
                    process.disk.io:
                        enabled: false
                    process.disk.operations:
                        enabled: false
                    process.handles:
                        enabled: false
                    process.memory.usage:
                        enabled: false
                    process.memory.utilization:
                        enabled: true
                    process.memory.virtual:
                        enabled: false
                    process.open_file_descriptors:
                        enabled: false
                    process.paging.faults:
                        enabled: false
                    process.signals_pending:
                        enabled: false
                    process.threads:
                        enabled: false
                mute_process_exe_error: true
                mute_process_io_error: false
                mute_process_name_error: true
                mute_process_user_error: false
    otlp/s-01JZ0JTP6PBPXPQJY6R3JZ6DC8:
        protocols:
            grpc:
                endpoint: 0.0.0.0:4317
                keepalive:
                    server_parameters:
                        max_connection_age: 1m0s
                        max_connection_age_grace: 5m0s
                        max_connection_idle: 1m0s
                        time: 2h
                        timeout: 20s
                max_recv_msg_size_mib: 20
            http:
                endpoint: 0.0.0.0:4318
processors:
    batch/gw: null
    metricstransform/_agent_health_metrics:
        transforms:
            - action: update
              include: process.cpu.utilization
              match_type: strict
              operations:
                - action: aggregate_labels
                  aggregation_type: sum
                  label_set: []
            - action: update
              include: (.*)$$
              match_type: regexp
              new_name: agent_health_metrics_$$1
    snapshotprocessor: null
    snapshotprocessor/_d0_gw-0: null
    snapshotprocessor/_s0_source0_01JZ0JTP6PBPXPQJY6R3JZ6DC8: null
    throughputmeasurement/_d0_logs_gw-0:
        bindplane_extension: bindplane
        enabled: true
        extra_labels: {}
        sampling_ratio: 1
    throughputmeasurement/_d0_metrics_gw-0:
        bindplane_extension: bindplane
        enabled: true
        extra_labels: {}
        sampling_ratio: 1
    throughputmeasurement/_d0_traces_gw-0:
        bindplane_extension: bindplane
        enabled: true
        extra_labels: {}
        sampling_ratio: 1
    throughputmeasurement/_d1_logs_gw-0:
        bindplane_extension: bindplane
        enabled: true
        extra_labels: {}
        sampling_ratio: 1
    throughputmeasurement/_d1_metrics_gw-0:
        bindplane_extension: bindplane
        enabled: true
        extra_labels: {}
        sampling_ratio: 1
    throughputmeasurement/_d1_traces_gw-0:
        bindplane_extension: bindplane
        enabled: true
        extra_labels: {}
        sampling_ratio: 1
    throughputmeasurement/_s0_logs_source0_01JZ0JTP6PBPXPQJY6R3JZ6DC8:
        bindplane_extension: bindplane
        enabled: true
        extra_labels:
            destinations: '|gw|'
            usage: "true"
        measure_log_raw_bytes: true
        sampling_ratio: 1
    throughputmeasurement/_s0_metrics_source0_01JZ0JTP6PBPXPQJY6R3JZ6DC8:
        bindplane_extension: bindplane
        enabled: true
        extra_labels:
            destinations: '|gw|'
            usage: "true"
        measure_log_raw_bytes: true
        sampling_ratio: 1
    throughputmeasurement/_s0_traces_source0_01JZ0JTP6PBPXPQJY6R3JZ6DC8:
        bindplane_extension: bindplane
        enabled: true
        extra_labels:
            destinations: '|gw|'
            usage: "true"
        measure_log_raw_bytes: true
        sampling_ratio: 1
    throughputmeasurement/_s1_logs_source0_01JZ0JTP6PBPXPQJY6R3JZ6DC8:
        bindplane_extension: bindplane
        enabled: true
        extra_labels: {}
        sampling_ratio: 1
    throughputmeasurement/_s1_metrics_source0_01JZ0JTP6PBPXPQJY6R3JZ6DC8:
        bindplane_extension: bindplane
        enabled: true
        extra_labels: {}
        sampling_ratio: 1
    throughputmeasurement/_s1_traces_source0_01JZ0JTP6PBPXPQJY6R3JZ6DC8:
        bindplane_extension: bindplane
        enabled: true
        extra_labels: {}
        sampling_ratio: 1
    transform/_agent_health_metrics:
        error_mode: ignore
        metric_statements:
            - context: datapoint
              statements:
                - set(attributes["agent"], "0197c12a-ce31-70ed-afd3-8b541b29b186")
                - set(attributes["configuration"], "gw")
                - delete_key(resource.attributes, "process.command")
                - delete_key(resource.attributes, "process.command_line")
                - delete_key(resource.attributes, "process.executable.name")
                - delete_key(resource.attributes, "process.executable.path")
                - delete_key(resource.attributes, "process.owner")
                - delete_key(resource.attributes, "process.parent_pid")
                - delete_key(resource.attributes, "process.pid")
    transform/gw__drop-raw-copy:
        log_statements:
            - context: log
              statements:
                - delete_key(attributes, "log.record.original")
connectors:
    forward/d-d-gw: null
exporters:
    otlp/gw:
        compression: gzip
        endpoint: external-gw:4317
        retry_on_failure:
            enabled: true
            initial_interval: 5s
            max_elapsed_time: 300s
            max_interval: 30s
        sending_queue:
            enabled: true
            num_consumers: 10
            queue_size: 5000
        timeout: 30s
        tls:
            insecure: true
    otlphttp/_agent_health_metrics:
        endpoint: https://app.bindplane.com/v1/agents/0197c12a-ce31-70ed-afd3-8b541b29b186/health
        headers:
            X-Bindplane-Account-ID: 01JFJGVKWHN97VN1J65YC37SSD
        retry_on_failure:
            enabled: false
        sending_queue:
            enabled: false
        timeout: 10s
service:
    pipelines:
        logs/d-d-gw:
            receivers:
                - forward/d-d-gw
            processors:
                - throughputmeasurement/_d0_logs_gw-0
                - snapshotprocessor/_d0_gw-0
                - throughputmeasurement/_d1_logs_gw-0
                - batch/gw
                - transform/gw__drop-raw-copy
                - snapshotprocessor
            exporters:
                - otlp/gw
        logs/s-01JZ0JTP6PBPXPQJY6R3JZ6DC8:
            receivers:
                - otlp/s-01JZ0JTP6PBPXPQJY6R3JZ6DC8
            processors:
                - throughputmeasurement/_s0_logs_source0_01JZ0JTP6PBPXPQJY6R3JZ6DC8
                - snapshotprocessor/_s0_source0_01JZ0JTP6PBPXPQJY6R3JZ6DC8
                - throughputmeasurement/_s1_logs_source0_01JZ0JTP6PBPXPQJY6R3JZ6DC8
            exporters:
                - forward/d-d-gw
        metrics/_agent_health_metrics:
            receivers:
                - hostmetrics/_agent_health_metrics
            processors:
                - metricstransform/_agent_health_metrics
                - transform/_agent_health_metrics
            exporters:
                - otlphttp/_agent_health_metrics
        metrics/d-d-gw:
            receivers:
                - forward/d-d-gw
            processors:
                - throughputmeasurement/_d0_metrics_gw-0
                - snapshotprocessor/_d0_gw-0
                - throughputmeasurement/_d1_metrics_gw-0
                - batch/gw
                - snapshotprocessor
            exporters:
                - otlp/gw
        metrics/s-01JZ0JTP6PBPXPQJY6R3JZ6DC8:
            receivers:
                - otlp/s-01JZ0JTP6PBPXPQJY6R3JZ6DC8
            processors:
                - throughputmeasurement/_s0_metrics_source0_01JZ0JTP6PBPXPQJY6R3JZ6DC8
                - snapshotprocessor/_s0_source0_01JZ0JTP6PBPXPQJY6R3JZ6DC8
                - throughputmeasurement/_s1_metrics_source0_01JZ0JTP6PBPXPQJY6R3JZ6DC8
            exporters:
                - forward/d-d-gw
        traces/d-d-gw:
            receivers:
                - forward/d-d-gw
            processors:
                - throughputmeasurement/_d0_traces_gw-0
                - snapshotprocessor/_d0_gw-0
                - throughputmeasurement/_d1_traces_gw-0
                - batch/gw
                - snapshotprocessor
            exporters:
                - otlp/gw
        traces/s-01JZ0JTP6PBPXPQJY6R3JZ6DC8:
            receivers:
                - otlp/s-01JZ0JTP6PBPXPQJY6R3JZ6DC8
            processors:
                - throughputmeasurement/_s0_traces_source0_01JZ0JTP6PBPXPQJY6R3JZ6DC8
                - snapshotprocessor/_s0_source0_01JZ0JTP6PBPXPQJY6R3JZ6DC8
                - throughputmeasurement/_s1_traces_source0_01JZ0JTP6PBPXPQJY6R3JZ6DC8
            exporters:
                - forward/d-d-gw
    telemetry:
        metrics:
            readers:
                - pull:
                    exporter:
                        prometheus:
                            host: localhost
                            port: 8888
            level: normal
        resource:
            service.instance.id: 0197c12a-ce31-70ed-afd3-8b541b29b186
